/**
 * Created by AllenFeng on 2017/3/24.
 */

const user = {
    GET_USER: 'GET_USER',
    LOGIN_USER: 'LOGIN_USER',
    ISFETCH: 'ISFETCH',
    LOAD_AUTH_IMG: 'LOAD_AUTH_IMG',
    VERIFY_CODE: 'VERIFY_CODE',
    SEND_MAIL: 'SEND_MAIL',
    RESET_AUTH_STATUS: 'RESET_AUTH_STATUS',
    VERIFY_MAIL_CODE: 'VERIFY_MAIL_CODE',
    REGIST_USER: 'REGIST_USER',
    EDIT_PASSWORD: 'EDIT_PASSWORD',
    THIRD_LOGIN: 'THIRD_LOGIN',
    BIND_USER: 'BIND_USER',
    CLEAR_TOKEN: 'CLEAR_TOKEN',
    ADD_ROLE:'ADD_ROLE',
    EDIT_ROLE:'EDIT_ROLE',
    REMOVE_ROLE:'REMOVE_ROLE',
    UPDATE_PASSWORD:'UPDATE_PASSWORD',
    UPDATE_USER:'UPDATE_USER',
    GET_ACCOUNT_LIST:'GET_ACCOUNT_LIST',
    UNBIND_THIRDPARTY_ACCOUNT:'UNBIND_THIRDPARTY_ACCOUNT',
    THIRD_BIND_INNER:'THIRD_BIND_INNER',
    CHANGE_LANG:'CHANGE_LANG'
}

const projects = {
    GET_MY_PROJECTS: 'GET_MY_PROJECTS',
    ADD_PROJECTS: 'ADD_PROJECTS',
    GET_PROJECT_DETAIL: 'GET_PROJECT_DETAIL',
    CHANGE_PROJECT_MEMBER_TAGS: 'CHANGE_PROJECT_MEMBER_TAGS',
    CHANGE_PROJECT_MEMBER_ROLE: 'CHANGE_PROJECT_MEMBER_ROLE',
    EXIT_PROJECT: 'EXIT_PROJECT',
    // SEARCH_TEAM: 'SEARCH_TEAM',
    INVITE_PROJECT_MEMBERS: 'INVITE_PROJECT_MEMBERS',
    EDIT_PROJECT: 'EDIT_PROJECT',
    LOAD_PROJECT_IMG: 'LOAD_PROJECT_IMG',
    DELETE_PROJECT: 'DELETE_PROJECT',
    REMOVE_PROJECT_MEMBER: 'REMOVE_PROJECT_MEMBER',
    TRANSFORM_PROJECT: 'TRANSFORM_PROJECT',
    GET_MEMBER_PROJECTS:'GET_MEMBER_PROJECTS',
    INIT_PROJECT:'INIT_PROJECT'
}

const slider = {
    OPEN_SLIDER: 'OPEN_SLIDER',
    CLOSE_SLIDER: 'CLOSE_SLIDER',
}

const teams={
    GET_MY_TEAMS:'GET_MY_TEAMS',
    LOAD_TEAM_IMG: 'LOAD_TEAM_IMG',
    GET_MEMBER_LIST:'GET_MEMBER_LIST',
    ADD_TEAMS:'ADD_TEAMS',
    GET_TEAM_DETAIL:'GET_TEAM_DETAIL',
    CHANGE_TEAM_MEMBER_TAGS: 'CHANGE_TEAM_MEMBER_TAGS',
    CHANGE_TEAM_MEMBER_ROLE: 'CHANGE_TEAM_MEMBER_ROLE',
    EXIT_TEAM: 'EXIT_TEAM',
    SEARCH_TEAM: 'SEARCH_TEAM',
    INVITE_TEAM_MEMBERS: 'INVITE_TEAM_MEMBERS',
    EDIT_TEAM: 'EDIT_TEAM',
    DELETE_TEAM: 'DELETE_TEAM',
    REMOVE_TEAM_MEMBER: 'REMOVE_TEAM_MEMBER',
    TRANSFORM_TEAM: 'TRANSFORM_TEAM',
    INIT_TEAM:'INIT_TEAM'
}

const scrum = {
    GET_BACKLOG_LIST: 'GET_BACKLOG_LIST',
    GET_CURRENT_BACKLOG_LIST:'GET_CURRENT_BACKLOG_LIST',
    ADD_BACKLOG: 'ADD_BACKLOG',
    EDIT_BACKLOG: 'EDIT_BACKLOG',
    GET_BACKLOG: 'GET_BACKLOG',
    GET_RELEASEANDSPRINT_LIST:'GET_RELEASEANDSPRINT_LIST',
    MOVE_BACKLOG:'MOVE_BACKLOG',
    DELETE_BACKLOG:'DELETE_BACKLOG',
    CHANGE_SPRINT:'CHANGE_SPRINT',
    SELECT_CURRENT_SPRINT:'SELECT_CURRENT_SPRINT',
    RESET_CURRENT_BACKLOG_LIST:'RESET_CURRENT_BACKLOG_LIST',
    CREATE_RELEASE:'CREATE_RELEASE',
    CHANGE_RELEASE:'CHANGE_RELEASE',
    CREATE_SPRINT:'CREATE_SPRINT',
    DELETE_SPRINT: 'DELETE_SPRINT',
    GET_WHITEBOARD_LIST:'GET_WHITEBOARD_LIST',
    GET_CURRENTRELEASEANDSPRINT:'GET_CURRENTRELEASEANDSPRINT',
    ADD_TASK:'ADD_TASK',
    EDIT_TASK:'EDIT_TASK',
    DELETE_TASK:'DELETE_TASK',
    EDIT_TASK_STATE:'EDIT_TASK_STATE',
    GET_TASK_LOG_LIST:'GET_TASK_LOG_LIST',
    INIT_WHITEBOARD:'INIT_WHITEBOARD'
};
const timeSheet = {
    GET_MY_TIMESHEET: 'GET_MY_TIMESHEET',
    CREATE_TIMESHEET_TASKS: 'CREATE_TIMESHEET_TASKS',
    SUBMIT_TIMESHEET: 'SUBMIT_TIMESHEET',
    APPROVE_TIMESHEET: 'APPROVE_TIMESHEET',
    DELETE_TIMESHEET_TASK: 'DELETE_TIMESHEET_TASK',
    MODIFY_TIMESHEET_TASK: 'MODIFY_TIMESHEET_TASK',
    CHANGE_TASK_TYPE:'CHANGE_TASK_TYPE',
    GET_QUERY_PARAMS: 'GET_QUERY_PARAMS',
    CHECK_TIMESHEET_LIST: 'CHECJ_TIMESHEET_LIST',
    QUERY_REPORT_TIMESHEET_LIST: 'QUERY_REPORT_TIMESHEET_LIST',
    QUERY_CHECK_TIMESHEET_LIST: 'QUERY_CHECK_TIMESHEET_LIST',
    MY_COMPLETE_TASKLIST: 'MY_COMPLETE_TASKLIST',
    SELECT_IMPORT_TASK: 'SELECT_IMPORT_TASK',
    RESET_SELECT_IMPORT_TASK: 'RESET_SELECT_IMPORT_TASK'
}

export {
    user,
    projects,
    slider,
    scrum,
    teams,
    timeSheet
}